### ISSUE TITLE
write and test PyDM widget types

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/adl2pydm#16]
these are the (internal, MEDM) widget types to write in PyDM:

* [x] arc
* [x] bar
* [x] byte (Byte Monitor)
* [x] cartesian plot
* [x] choice button
* [x] composite
* [x] embedded display  (see #17 *and* https://github.com/slaclab/pydm/issues/565)
* [x] image
* [x] indicator (Scale Monitor)
* [x] menu
* [x] message button
* [x] meter
* [x] oval
* [x] polygon
* [x] polyline
* [x] rectangle
* [x] related display
* [x] shell command
* [x] strip chart
* [x] text
* [x] text entry
* [x] text update (Text Monitor)
* [x] valuator (Slider)
* [x] wheel switch

**Comment by prjemian** [comment]
Wheel switch (spinbox) has a [`format`](https://epics.anl.gov/EpicsDocumentation/ExtensionsManuals/MEDM/MEDM.html#Label) string that is probably not supported in Qt's [QDoubleSpinBox](https://doc.qt.io/qt-5/qdoublespinbox.html#details) widget.

Need some experience using that widget before we can declare the writer finished on it.

**Comment by prjemian** [comment]
Filed these issues with [PyDM](https://github.com/slaclab/pydm):

* How to scale font size to widget geometry? https://github.com/slaclab/pydm/issues/574
* PyDMByteIndicator: bigEndian ignored in Horizontal orientation: https://github.com/slaclab/pydm/issues/576
* consistency problems: https://github.com/slaclab/pydm/issues/577
* PyDMDrawingPolyline widget: https://github.com/slaclab/pydm/issues/578
* PyDMDrawingIrregularPolygon widget: https://github.com/slaclab/pydm/issues/579

**Comment by prjemian** [comment]
Some drawing widgets (notably polygon and polyline) each need to be drawn on a single *canvas* but have no corresponding widget type available now in PyDM.

The font sizing problem is a nuisance but not a show stopper.

The consistency problems are a nuisance to the programmer but can be resolved, albeit with [messy code](https://github.com/slaclab/pydm/issues/577#issuecomment-554221678).

**Comment by prjemian** [comment]
Note this [BUG](https://github.com/slaclab/pydm/pull/580#issuecomment-554664027) in adl2pydm

**Comment by prjemian** [comment]
No widget for the *shell command* yet, where the number of commands is more than one.

**Comment by prjemian** [comment]
Checkpoint:  `bar` and `oval` widgets are yet to be handled.  Been testing conversion of the screens from the docker IOC and resolving additional problems as identified.  Here's a scan run entirely from the PyDM GUI (although the swait record, used as a noisy detector signal, was configured from bluesky).  Some rough edges remain but: Very usable!

![Clipboard01](https://user-images.githubusercontent.com/2279984/76981954-3bf8ba80-6909-11ea-9cf9-ec624a5ff300.jpg)


Big thanks to @hhslepicka, @mattgibbs, and [the rest the PyDM developers!](https://github.com/slaclab/pydm/graphs/contributors)

**Comment by hhslepicka** [comment]
@prjemian they look great! 
For the bar and oval, do you happen to have a screenshot on how they look like?

**Comment by prjemian** [comment]
Not anticipating any difficulty.  Just represents state of things when I had to concentrate on other activities last November.  Here's a sample of ovals and bars.

--------

### oval

![Clipboard02](https://user-images.githubusercontent.com/2279984/77096336-353b7780-69dd-11ea-8f6f-d21b2aebfcc3.jpg)

The ovals are either static or connected to a PV (for visibility rules).  This is MEDM's widget config for one of these ovals (the open one with red dashed line):
![Clipboard03](https://user-images.githubusercontent.com/2279984/77096441-59975400-69dd-11ea-91af-aa818389b2cf.jpg)

--------

### bar monitor

The *bars* are monitor widgets (means they are always connected to a PV to display its value).  Should be an integer or float PV (which as HOPR and LOPR which define the range of the bar) or a motor PV (which defines HLM and LLM).  Here, I made a custom IOC for the demo PV

<details>

file: `medm.db`, run IOC with `softIoc -d medm.db`

```
record(ao, "demo:bar") {
    field(HOPR, 255.0)
    field(LOPR, 0.0)
    field(VAL, 0.0)
    field(EGU, "dimensionless")
}
```
</details>

This is MEDM's widget config for one of these bars (the vertical one, second from left in upper row, with red at the top instead of the bottom):
![Clipboard01](https://user-images.githubusercontent.com/2279984/77097026-273a2680-69de-11ea-9248-20c897b73748.jpg)

**Comment by prjemian** [comment]
For documentation, I am attaching both `.db` and `.adl` file here (with `.txt` added so GH accepts them):
----

[medm.db.txt](https://github.com/BCDA-APS/adl2pydm/files/4356105/medm.db.txt)

----

[medm-demo.adl.txt](https://github.com/BCDA-APS/adl2pydm/files/4356109/medm-demo.adl.txt)

**Comment by hhslepicka** [comment]
I think we got you covered with some widgets that we have:
For Bar you can use: https://github.com/slaclab/pydm/blob/master/pydm/widgets/slider.py#L10
For Oval you can use: https://github.com/slaclab/pydm/blob/master/pydm/widgets/drawing.py#L749

Let me know if we are missing something.

**Comment by prjemian** [comment]
The `PyDMSlider` widget is for input.  MEDM's `bar` widget is a monitor so it needs to be read-only.  That's not an option for the `PyDMSlider`.  Perhaps [`PyDMScaleIndicator`](https://github.com/slaclab/pydm/blob/6bc984039f9146a263d46222c7589b6451d9b1e7/pydm/widgets/scale.py#L367)?

**Comment by hhslepicka** [comment]
Correct. In this case the ScaleIndicator is what you want to use

**Comment by prjemian** [comment]
Need to confirm `polygon` support.

**Comment by prjemian** [comment]
Support for MEDM's polygon must wait until the `PyDMDrawingIrregularPolygon` widget (https://github.com/slaclab/pydm/issues/579) is ready.  The `PyDMDrawingPolygon` assumes all sides are of equal length and the curvature does not change (sides do not cross).

**Comment by prjemian** [comment]
The `testDisplay.adl` has two examples of filled polygons with lines that do not cross.  Need a new example.

**Comment by prjemian** [comment]
Pivoting the polygon to be a polyline for now, until https://github.com/slaclab/pydm/issues/579 is ready.  One consequence is that it is only outline over the points.  The solid-filled option not available now.

**Comment by prjemian** [comment]
Polygons demo screen (green check mark comes when PV within 0.5 of RBV, orange arrow when RBV>127).
![Clipboard01](https://user-images.githubusercontent.com/2279984/77262998-f3246700-6c64-11ea-8fd0-28a8f311f4c7.jpg)

**Comment by prjemian** [comment]
Black, purple, and blue should have `fill=solid` -- on TODO list

**Comment by prjemian** [comment]
I'm declaring victory here.
