### ISSUE TITLE
Does MEDM have an "embedded display" widget?

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/adl2pydm#17]
Cannot find this in MEDM source code nor in any of the synApps or APS adlsys screen collections.

**Comment by prjemian** [comment]
Search of local files (including MEDM source code, synApps screens, and adlsys screens from APS):

```
(base) mintadmin@mint-vm:~/.../eclipse/adl2pydm$ locate .adl | wc -l
7158
(base) mintadmin@mint-vm:~/.../eclipse/adl2pydm$ grep embedded `locate .adl`
grep: /usr/local/epics/adlsys/srbpm/s35App/scaler16_full.adl: No such file or directory
grep: /usr/local/epics/adlsys/srbpm/s35App/scaler16_full_calc.adl: No such file or directory
grep: /usr/local/epics/adlsys/srbpm/s35App/scaler16_more.adl: No such file or directory
grep: /usr/local/epics/adlsys/srbpm/s35App/scaler_full_calc.adl: No such file or directory
```

**Comment by MarkRivers** [comment]
What is meant by an "embedded display" widget?

**Comment by prjemian** [comment]
Somehow, I picked up the concept of a MEDM "embedded display" widget (embed the content of one screen within another) for this project but now cannot find any evidence of such.  This issue was filed to document removal of the *embedded display* widget from this code.  PyDM has an embedded widget and likely this was an early confusion for me.  In MEDM, the same concept is achieved using a "composite" widget with an ADL file name given as value to the *composite file* property.

**Comment by MarkRivers** [comment]
I understand, thanks.
