### ISSUE TITLE
make MEDM sampler file

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/adl2pydm#27]
create a MEDM file with all the known widgets, for testing this code

**Comment by prjemian** [comment]
perhaps a sample for each different object in the palette, with variations as appropriate

**Comment by MarkRivers** [comment]
The EPICS Windows Tools comes with such a sample file, testDisplay.adl.  It has a number of other test files for related displays, widget, etc.

**Comment by prjemian** [comment]
Thanks!  Time saver.

**Comment by prjemian** [comment]
Looking here: https://epics.anl.gov/distributions/win32/index.php.  This file (CA-3.15.6-windows-x64.zip) only contains executables and libraries.

Looking further down that page, there are `.msi` installer files as well.  The notes for 1.44 (most recent version before the author retired) mentions included `.adl` files.  Source code is not online.  Must install one of them to get at the file desired.

**Comment by prjemian** [comment]
This one: [`EPICSWindowsTools1.44-x64.msi`](https://epics.anl.gov/download/distributions/EPICSWindowsTools1.44-x64.msi)
