### ISSUE TITLE
sscan scatter plot has no data

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/adl2pydm#45]
expected data not shown in the scatter plot from the sscan screen

* upper: PyDM
* lower: MEDM

![Clipboard01](https://user-images.githubusercontent.com/2279984/76969029-d6500280-68f7-11ea-83b9-b02b6b06431d.jpg)

**Comment by prjemian** [comment]
Detector PV did not connect.  Macros?
![Clipboard01](https://user-images.githubusercontent.com/2279984/76969318-3c3c8a00-68f8-11ea-858b-6be42ff1585d.jpg)

**Comment by prjemian** [comment]
One problem: `$()` should use curly braces: `${}`

Not the real problem, though.  The `*PV` addresses are connected while the `*CA` addresses are not.  Unexpanded macros?

**Comment by prjemian** [comment]
Also expand macros in the *yLabels* (and *xLabels*)

**Comment by prjemian** [comment]
All channels connect, still no data:
![Clipboard01](https://user-images.githubusercontent.com/2279984/76970784-5e370c00-68fa-11ea-8ee2-685ab0053dee.jpg)

**Comment by prjemian** [comment]
Of course!  The data here are *waveforms* so we need to be using the `PyDMWaveformPlot` widget instead.

How can a screen translator be smart enough to know this *a priori*?  MEDM handles both scaler PVs and waveform PVs from the same *cartesian plot* widget.

@hhslepicka,  @mattgibbs , @timmooney: Any insight how a display screen translator can decide if given PVs come from a waveform PV (so need to use the `PyDMScatterPlot` widget) or a scalar PV (need to use the `PyDMScatterPlot` widget)?

**Comment by prjemian** [comment]
This would be easy if the translator had access to an IOC with those PVs available.  Since the translators run in an automation (likely even in CI), can't count on an IOC to be available.

**Comment by prjemian** [comment]
@MarkRivers : Might you have some ideas how to resolve the [problem](https://github.com/BCDA-APS/adl2pydm/issues/45#issuecomment-600664567) here?

**Comment by MarkRivers** [comment]
> MEDM handles both scaler PVs and waveform PVs from the same cartesian plot widget.

I think I've only used it with waveform PVs.  How does it handle scaler PVs?

**Comment by prjemian** [comment]
See
https://epics.anl.gov/EpicsDocumentation/ExtensionsManuals/MEDM/MEDM.html#CartesianPlot

Look for section titled *Kinds of XY Traces*

**Comment by prjemian** [comment]
not a section, that's a table - very detailed explanation there

**Comment by prjemian** [comment]
I'm thinking that we'll probably need a new plotting widget in PyDM (for compatibility with MEDM screens) that provides this capability.  Until then, the translator should default to `PyDMWaveformPlot` instead of  `PyDMScatterPlot`.

**Comment by prjemian** [comment]
Switching (manual edit) to the `PyDMWaveformPlot` widget, the plot data shows and is the same as MEDM
![Clipboard01](https://user-images.githubusercontent.com/2279984/76975264-511d1b80-6900-11ea-9b27-7a2cc933cdef.jpg)

**Comment by MarkRivers** [comment]
> Until then, the translator should default to PyDMWaveformPlot instead of PyDMScatterPlot.

I agree, I think the Cartesian plot is used much more with waveforms than scalers.  

Since most windows have at most one plot window (or if there is more than one they are usually all the same type) then you could have a command line option for the translator that tells it to use PyDMScatterPlot rather than the default PyDMWaveformPlot.

**Comment by prjemian** [comment]
Good suggestion.
