### ISSUE TITLE
remove pyqtdesignerpath import test from conda-forge recipe

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/adl2pydm#91]
From the initial [recipe](https://github.com/conda-forge/staged-recipes/pull/18908/files#diff-059efd4adc8db746ff738f9cbc538dd6ae14c62962ca907f6a1757ed08a3eb43R26-R29) created by grayskull:

```py
test:
  imports:
    - adl2pydm
    - pyqtdesignerpath
```

**Comment by prjemian** [comment]
see: https://github.com/conda-forge/adl2pydm-feedstock/pull/1

**Comment by klauer** [comment]
Great!
